"""Initial schema with all models

Revision ID: f35fcf511ab5
Revises:
Create Date: 2025-12-17 13:06:52.016852

"""
from collections.abc import Sequence

import pgvector.sqlalchemy.vector
import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f35fcf511ab5'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Enable pgvector extension
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.VARCHAR(21), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True),
    sa.Column('bgg_id', sa.Integer(), nullable=True),
    sa.Column('bgg_url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_bgg_id'), 'games', ['bgg_id'], unique=True)
    op.create_index(op.f('ix_games_name'), 'games', ['name'], unique=False)
    op.create_index(op.f('ix_games_slug'), 'games', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.VARCHAR(21), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('verification_tokens',
    sa.Column('identifier', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('expires', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('identifier')
    )
    op.create_index(op.f('ix_verification_tokens_token'), 'verification_tokens', ['token'], unique=False)
    op.create_table('resources',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.VARCHAR(21), nullable=False),
    sa.Column('game_id', sa.VARCHAR(21), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('original_filename', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('READY', 'QUEUED', 'PROCESSING', 'COMPLETED', 'FAILED', name='resourcestatus'), nullable=False),
    sa.Column('resource_type', sa.Enum('RULEBOOK', 'EXPANSION', 'FAQ', 'ERRATA', 'REFERENCE', name='resourcetype'), nullable=False),
    sa.Column('pdf_extractor', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('processing_stage', sa.Enum('INGEST', 'VISION', 'CLEANUP', 'METADATA', 'EMBED', 'FINALIZE', name='processingstage'), nullable=True),
    sa.Column('current_run_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('processed_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('image_count', sa.Integer(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resources_game_id'), 'resources', ['game_id'], unique=False)
    op.create_table('attachments',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.VARCHAR(21), nullable=False),
    sa.Column('game_id', sa.VARCHAR(21), nullable=False),
    sa.Column('resource_id', sa.VARCHAR(21), nullable=False),
    sa.Column('type', sa.Enum('IMAGE', name='attachmenttype'), nullable=False),
    sa.Column('mime_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('blob_key', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('bbox', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('detected_type', sa.Enum('DIAGRAM', 'TABLE', 'PHOTO', 'ICON', 'DECORATIVE', name='detectedtype'), nullable=True),
    sa.Column('is_good_quality', sa.Enum('GOOD', 'BAD', name='qualityrating'), nullable=True),
    sa.Column('ocr_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attachments_game_id'), 'attachments', ['game_id'], unique=False)
    op.create_index(op.f('ix_attachments_resource_id'), 'attachments', ['resource_id'], unique=False)
    op.create_table('fragments',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.VARCHAR(21), nullable=False),
    sa.Column('game_id', sa.VARCHAR(21), nullable=False),
    sa.Column('resource_id', sa.VARCHAR(21), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sa.Enum('TEXT', 'IMAGE', 'TABLE', name='fragmenttype'), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('section', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('attachment_id', sa.VARCHAR(21), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.Column('synthetic_questions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('answer_types', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('images', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['attachment_id'], ['attachments.id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('fragment_embedding_idx', 'fragments', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('fragment_search_vector_idx', 'fragments', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_fragments_game_id'), 'fragments', ['game_id'], unique=False)
    op.create_index(op.f('ix_fragments_resource_id'), 'fragments', ['resource_id'], unique=False)
    op.create_table('embeddings',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('fragment_id', sa.VARCHAR(21), nullable=False),
    sa.Column('game_id', sa.VARCHAR(21), nullable=False),
    sa.Column('resource_id', sa.VARCHAR(21), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
    sa.Column('type', sa.Enum('CONTENT', 'QUESTION', name='embeddingtype'), nullable=False),
    sa.Column('question_index', sa.Integer(), nullable=True),
    sa.Column('question_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fragment_id'], ['fragments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('embedding_fragment_type_idx', 'embeddings', ['fragment_id', 'type'], unique=False)
    op.create_index('embedding_vector_idx', 'embeddings', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index(op.f('ix_embeddings_fragment_id'), 'embeddings', ['fragment_id'], unique=False)
    op.create_index(op.f('ix_embeddings_game_id'), 'embeddings', ['game_id'], unique=False)
    op.create_index(op.f('ix_embeddings_resource_id'), 'embeddings', ['resource_id'], unique=False)
    # ### end Alembic commands ###

    # Create function and trigger for auto-updating fragment search_vector
    op.execute("""
        CREATE OR REPLACE FUNCTION update_fragment_search_vector()
        RETURNS trigger AS $$
        BEGIN
            NEW.search_vector := to_tsvector('english', NEW.content);
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
    """)
    op.execute("""
        CREATE TRIGGER fragment_search_vector_update
        BEFORE INSERT OR UPDATE ON fragments
        FOR EACH ROW
        EXECUTE FUNCTION update_fragment_search_vector();
    """)


def downgrade() -> None:
    # Drop trigger and function first
    op.execute("DROP TRIGGER IF EXISTS fragment_search_vector_update ON fragments")
    op.execute("DROP FUNCTION IF EXISTS update_fragment_search_vector()")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_embeddings_resource_id'), table_name='embeddings')
    op.drop_index(op.f('ix_embeddings_game_id'), table_name='embeddings')
    op.drop_index(op.f('ix_embeddings_fragment_id'), table_name='embeddings')
    op.drop_index('embedding_vector_idx', table_name='embeddings', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index('embedding_fragment_type_idx', table_name='embeddings')
    op.drop_table('embeddings')
    op.drop_index(op.f('ix_fragments_resource_id'), table_name='fragments')
    op.drop_index(op.f('ix_fragments_game_id'), table_name='fragments')
    op.drop_index('fragment_search_vector_idx', table_name='fragments', postgresql_using='gin')
    op.drop_index('fragment_embedding_idx', table_name='fragments', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('fragments')
    op.drop_index(op.f('ix_attachments_resource_id'), table_name='attachments')
    op.drop_index(op.f('ix_attachments_game_id'), table_name='attachments')
    op.drop_table('attachments')
    op.drop_index(op.f('ix_resources_game_id'), table_name='resources')
    op.drop_table('resources')
    op.drop_index(op.f('ix_verification_tokens_token'), table_name='verification_tokens')
    op.drop_table('verification_tokens')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_games_slug'), table_name='games')
    op.drop_index(op.f('ix_games_name'), table_name='games')
    op.drop_index(op.f('ix_games_bgg_id'), table_name='games')
    op.drop_table('games')
    # ### end Alembic commands ###
