"""add_processing_metadata_to_resources

Revision ID: f363b308d775
Revises: f35fcf511ab5
Create Date: 2025-12-17 14:52:58.845735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f363b308d775'
down_revision: Union[str, None] = 'f35fcf511ab5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resources', sa.Column('processing_metadata', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resources', 'processing_metadata')
    # ### end Alembic commands ###
